import type { Category, Guide, Article } from '@/lib/types';

export const MOCK_CATEGORIES: Category[] = [
  { slug: 'all', name: 'All' },
  { slug: 'beginner', name: 'Beginner' },
  { slug: 'money', name: 'Money' },
  { slug: 'collectibles', name: 'Collectibles' },
  { slug: 'missions', name: 'Missions' },
  { slug: 'vehicles', name: 'Vehicles' },
  { slug: 'map', name: 'Map' },
  { slug: 'news', name: 'News' },
];

const G = (s: string) => s; // gradient passthrough for readability

export const MOCK_GUIDES: Guide[] = [
  // Deliberately empty pre-launch. Nothing publishes as a guide before it can
  // be verified in-game. /guides carries the Guides Desk roadmap instead.
  // The full guide system (cards, tracker chips, articles) is built and waiting.
];

export const MOCK_ARTICLES: Article[] = [
  // ------------------------------------------------------------------
  // LATEST NEWS: verified. Facts strictly separated from rumour.
  // ------------------------------------------------------------------
  {
    kind: 'article',
    slug: 'everything-confirmed',
    title: 'GTA 6: Everything confirmed so far',
    kicker: 'The big read',
    category: 'news',
    excerpt: 'Every fact Rockstar has actually confirmed about GTA 6, in one living list. No guesses, checked and dated.',
    updatedAt: '2026-07-02',
    readingMins: 8,
    gradient: 'linear-gradient(150deg,#FF2E88,#8A4FFF 55%,#1FE5D6)',
    motif: 'skyline',
    heroImage: { src: '/media/gtavi-vice-city-skyline.jpg', alt: 'Vice City skyline at dusk, neon along the beachfront', credit: 'Rockstar Games' },
    body: [
      { type: 'p', text: 'This is the living list of everything Rockstar has officially confirmed about Grand Theft Auto VI. If it is not confirmed, it is not on this page. The unconfirmed stuff lives in the Rumour Mill, clearly labelled. Last full check: 2 July 2026.' },
      { type: 'h2', text: 'Confirmed' },
      { type: 'ul', items: [
        'Release date: Thursday 19 November 2026, on PS5 and Xbox Series X|S.',
        'Dual protagonists: Jason Duval and Lucia Caminos. Lucia is the first playable female lead of the modern era.',
        'Setting: the state of Leonida, centred on a modern Vice City.',
        'Editions: Standard (£69.99) and Ultimate (£89.99). Standard owners can buy the Ultimate upgrade at any time.',
        'Every pre-order before 20 November gets the Vintage Vice City Pack; digital pre-orders also include one month of GTA+, redeemable within 180 days.',
        'Pre-loading opens 12 November. Boxed copies contain a download code rather than a disc, and go on sale from 12 November.',
        'The official cover art landed in June, and Rockstar dropped more than 60 screenshots alongside pre-orders opening on 25 June. Its biggest image release for the game so far.',
        'Rockstar describes the launch as a single-player experience, with the online component to follow.',
      ] },
      { type: 'h2', text: 'Not yet confirmed' },
      { type: 'ul', items: [
        'A PC version. No announcement, no date, no specs. Anything you see quoted is a guess.',
        'The online mode’s name, structure, or timing beyond “to follow”.',
        'Performance modes and frame rates on any console.',
        'The install size, and exact launch unlock times by region.',
      ] },
      { type: 'p', text: 'Sources: Rockstar Newswire announcements, 18-25 June 2026, and the official Grand Theft Auto VI site.' },
    ],
  },
  {
    kind: 'article',
    slug: 'which-edition-to-preorder',
    title: 'Which edition should you pre-order? (UK)',
    kicker: 'Buying',
    category: 'news',
    excerpt: 'Standard or Ultimate? Box or digital? The UK pre-order picture, with the pricing that actually matters.',
    updatedAt: '2026-07-02',
    readingMins: 7,
    isNew: true,
    gradient: 'linear-gradient(150deg,#1FE5D6,#8A4FFF)',
    motif: 'money',
    heroImage: { src: '/media/gtavi-ultimate-edition.jpg', alt: 'GTA VI Ultimate Edition contents', credit: 'Rockstar Games' },
    gallery: [
      { src: '/media/gtavi-cheetah.jpg', alt: 'The Grotti Cheetah, Ultimate Edition exclusive', credit: 'Rockstar Games' },
      { src: '/media/gtavi-squalo.jpg', alt: 'The Squalo speedboat', credit: 'Rockstar Games' },
      { src: '/media/gtavi-stock305.jpg', alt: 'Stock 305 muscle car', credit: 'Rockstar Games' },
      { src: '/media/gtavi-willie.jpg', alt: 'One Eyed Willie off-roader', credit: 'Rockstar Games' },
      { src: '/media/gtavi-rideout.jpg', alt: 'Rideout Customs', credit: 'Rockstar Games' },
      { src: '/media/gtavi-vice-city-style.jpg', alt: 'Vice City Style outfits', credit: 'Rockstar Games' },
    ],
    body: [
      { type: 'p', text: 'Two editions, a boxed option that is really a download code, and a handful of UK retailers. Here is how to decide.' },
      { type: 'h2', text: 'The editions' },
      { type: 'ul', items: [
        'Standard, £69.99. The base game plus the Vintage Vice City Pack pre-order bonus.',
        'Ultimate, £89.99. Adds an exclusive story collection: premium vehicles including the ’95 Grotti Cheetah, two exclusive vehicle mod shops, a Classic Car Collection commission, a signature salon for Jason’s facial hair and Lucia’s nails, the Stock 305 clothing store, and exclusive weapon variants including the Hawk & Little Morgan revolver.',
      ] },
      { type: 'p', text: 'One detail widely misreported elsewhere: the free month of GTA+ is not an Ultimate Edition perk. It comes with any digital pre-order, either edition, and must be redeemed within 180 days.' },
      { type: 'p', text: 'You can buy Standard now and upgrade to Ultimate later at any time, so there is no rush to the pricier edition if you are unsure.' },
      { type: 'h2', text: 'Boxed or digital?' },
      { type: 'ul', items: [
        'The boxed version contains a download code. There is no disc. It ships from 12 November so you can redeem and pre-load before launch.',
        'Digital pre-orders pre-load from 12 November and include the month of GTA+.',
      ] },
      { type: 'h2', text: 'One honest note on the Ultimate Edition' },
      { type: 'p', text: 'Locking whole in-game shops behind the £20 upgrade has drawn real criticism, and fair enough: it is the first time entire locations rather than items sit behind an edition paywall in this series. Rockstar has confirmed nothing in the Ultimate Edition is required to play or finish the game. Our straight read: if the customisation extras excite you, the upgrade path lets you decide after launch instead of at pre-order.' },
      { type: 'p', text: 'Sources: Rockstar Newswire edition announcement, 24 June 2026; UK storefront pricing confirmed 25 June 2026.' },
    ],
  },
  {
    kind: 'article',
    slug: 'no-disc-in-the-box',
    title: 'No disc in the box: the physical edition, explained',
    kicker: 'Hardware',
    category: 'news',
    excerpt: 'Boxed GTA 6 ships with a download code, not a disc. What is actually in the box, why Rockstar says it is doing it, and what it means for you.',
    updatedAt: '2026-07-02',
    readingMins: 5,
    isNew: true,
    gradient: 'linear-gradient(150deg,#FF9E45,#FF2E88 60%,#8A4FFF)',
    motif: 'disc',
    heroImage: { src: '/media/gtavi-vice-city-night.jpg', alt: 'A Vice City street at night', credit: 'Rockstar Games' },
    body: [
      { type: 'p', text: 'Confirmed with the edition reveal on 24 June: the boxed, physical version of Grand Theft Auto VI does not contain a game disc. Inside the retail case is a one-time download code.' },
      { type: 'h2', text: 'What is actually in the box' },
      { type: 'ul', items: [
        'A retail case and a code that unlocks the full digital download. The whole game installs to your console storage.',
        'Boxed copies go on sale from 12 November, a week early, specifically so buyers can redeem the code and pre-load before launch night.',
        'There is no disc-based play, and no lending or reselling the game once the code is redeemed.',
      ] },
      { type: 'h2', text: 'Why Rockstar says it is doing this' },
      { type: 'p', text: 'The stated reason is pre-loading. With a code in every box, everyone can have the game installed and ready the second it unlocks. No disc install on launch night. It also puts the disc-drive-less PS5 and Series S on exactly the same footing as every other console. Sony even re-shot a pre-order advert around a digital-edition PS5 after the announcement.' },
      { type: 'h2', text: 'What it means for you' },
      { type: 'ul', items: [
        'You need the storage free and a connection that can handle a very large download. Sort both before 12 November.',
        'Collectors get a box for the shelf; the traditional second-hand and lending market for this game is effectively gone.',
        'If launch-night play matters to you, pre-load from 12 November whichever route you buy.',
      ] },
      { type: 'p', text: 'Sources: Rockstar Newswire pre-order announcement, 24 June 2026.' },
    ],
  },
  {
    kind: 'article',
    slug: 'vintage-vice-city-pack',
    title: 'Everything in the Vintage Vice City Pack',
    kicker: 'Pre-order bonus',
    category: 'news',
    excerpt: 'Pre-order before 20 November and this pack is yours. The ’55 sedan, the Ocean Beach garage and the retro wardrobe, itemised.',
    updatedAt: '2026-07-02',
    readingMins: 4,
    gradient: 'linear-gradient(150deg,#FFC83D,#FF9E45 55%,#FF2E88)',
    motif: 'cassette',
    heroImage: { src: '/media/gtavi-vvcp-hero.jpg', alt: 'The Vintage Vice City Pack', credit: 'Rockstar Games' },
    gallery: [
      { src: '/media/gtavi-vvcp-montage.jpg', alt: 'Vintage Vice City Pack contents', credit: 'Rockstar Games' },
      { src: '/media/gtavi-vvcp-looks-1.jpg', alt: 'Exclusive Vice City look', credit: 'Rockstar Games' },
      { src: '/media/gtavi-vvcp-looks-2.jpg', alt: 'Exclusive Vice City look, full retro fit', credit: 'Rockstar Games' },
      { src: '/media/gtavi-stanier-1.jpg', alt: 'The classic Vapid Stanier', credit: 'Rockstar Games' },
      { src: '/media/gtavi-stanier-2.jpg', alt: 'Vapid Stanier detail', credit: 'Rockstar Games' },
      { src: '/media/gtavi-vvcp-pattern.jpg', alt: 'Vice City weapon pattern', credit: 'Rockstar Games' },
    ],
    body: [
      { type: 'p', text: 'The Vintage Vice City Pack is the pre-order bonus, and it is tied to ordering early rather than spending more: anyone who pre-orders before 20 November gets it, on either edition.' },
      { type: 'h2', text: 'What is in it' },
      { type: 'ul', items: [
        'The ’55 Vapid Stanier, a classic sedan built for cruising Shore Drive.',
        'The Shore Court personal garage, a stone’s throw from the sands of Ocean Beach.',
        'Retro outfits and hairstyles for both Jason and Lucia.',
        'A vintage weapon pattern echoing the excess of the old Vice City era.',
      ] },
      { type: 'h2', text: 'The extra for digital buyers' },
      { type: 'p', text: 'Pre-order digitally, either edition, and you also get a month of GTA+. Redeem it within 180 days of launch.' },
      { type: 'p', text: 'Worth being clear-eyed: this is cosmetic, nostalgic flavour rather than anything that changes how the game plays. A lovely callback for series veterans; not a reason to pre-order if you were otherwise waiting for reviews.' },
      { type: 'p', text: 'Sources: Rockstar Newswire edition announcement, 24 June 2026.' },
    ],
  },
  {
    kind: 'article',
    slug: 'screenshot-drop-what-it-confirms',
    title: 'The 60-screenshot drop: what it actually confirms',
    kicker: 'Analysis',
    category: 'news',
    excerpt: 'Rockstar’s biggest image release yet landed with pre-orders. Here is what the stills actually confirm, plus the one caveat worth keeping.',
    updatedAt: '2026-07-02',
    readingMins: 6,
    gradient: 'linear-gradient(150deg,#FF2E88,#FF9E45 60%,#FFC83D)',
    motif: 'palms',
    heroImage: { src: '/media/gtavi-leonida-keys.jpg', alt: 'Aerial view over the Leonida Keys', credit: 'Rockstar Games' },
    gallery: [
      { src: '/media/gtavi-vc-beach.jpg', alt: 'Vice City beachfront', credit: 'Rockstar Games' },
      { src: '/media/gtavi-keys-2.jpg', alt: 'The Leonida Keys causeway', credit: 'Rockstar Games' },
      { src: '/media/gtavi-gellhorn.jpg', alt: 'Port Gellhorn', credit: 'Rockstar Games' },
      { src: '/media/gtavi-kalaga.jpg', alt: 'Mount Kalaga National Park', credit: 'Rockstar Games' },
      { src: '/media/gtavi-grassrivers.jpg', alt: 'Grassrivers wetlands', credit: 'Rockstar Games' },
      { src: '/media/gtavi-ambrosia.jpg', alt: 'Ambrosia', credit: 'Rockstar Games' },
    ],
    body: [
      { type: 'p', text: 'Alongside pre-orders opening on 25 June, Rockstar published its biggest still-image release for the game so far: more than 60 screenshots, 51 of them on the official media page, largely built around the Ultimate Edition and the Vintage Vice City Pack.' },
      { type: 'h2', text: 'What the images genuinely confirm' },
      { type: 'ul', items: [
        'Character customisation runs far deeper than GTA 5. The stills show Jason and Lucia across dozens of hairstyles, outfits, tattoos and nail designs.',
        'Named in-world businesses, including Sara’s Unisex Salon and the Electric Fang tattoo shop.',
        'A spread of new vehicles and boats, plus vehicle and boat customisation.',
        'A deliberately ’80s-leaning retro aesthetic across the pre-order marketing. A clear nod to the original Vice City era.',
      ] },
      { type: 'h2', text: 'The caveat worth keeping' },
      { type: 'p', text: 'These are in-engine 4K stills published for marketing. Digital Foundry has publicly questioned whether they represent real-time output on launch consoles, noting the image quality suggests settings beyond what PS5 or Series X are likely to render live. Until Rockstar ships a gameplay trailer with a stated capture platform, treat the polish as marketing-grade rather than a performance promise.' },
      { type: 'p', text: 'Anything from the gallery that hardens into confirmed fact gets folded into our Everything Confirmed roundup; the frame-rate question lives where it belongs, in the Rumour Mill.' },
      { type: 'p', text: 'Sources: Rockstar Games media page, 24-25 June 2026; Digital Foundry commentary, June 2026.' },
    ],
  },


  {
    kind: 'article',
    slug: 'where-is-trailer-3',
    title: 'Where is GTA 6 Trailer 3?',
    kicker: 'Analysis',
    category: 'news',
    excerpt: 'Pre-orders came and went without it. Here is the realistic window, and why the next trailer carries more weight than the first two combined.',
    updatedAt: '2026-07-03',
    readingMins: 2,
    isNew: true,
    gradient: 'linear-gradient(150deg,#FF2E88,#8A4FFF)',
    motif: 'signal',
    heroImage: { src: '/media/gtavi-vc-street.jpg', alt: 'Vice City, the centre of Leonida', credit: 'Rockstar Games' },
    gallery: [{ src: '/media/gtavi-jason-lucia-a.jpg', alt: 'Jason and Lucia, the pair at the centre of it all', credit: 'Rockstar Games' }],
    body: [
      { type: 'p', text: 'Pre-orders opened on 25 June with the price and the editions, and no Trailer 3. That was almost certainly deliberate. Take-Two boss Strauss Zelnick has said the campaign is social-first and will not follow the old GTA 5 script, so bundling a trailer with the pre-order news would have spent two huge moments on one day. Expect the trailer to stand on its own.' },
      { type: 'h2', text: 'The likeliest window' },
      { type: 'p', text: 'Most informed guesses point to mid or late July, with some stretching to mid-August. The World Cup final on 19 July is the obvious target, because dropping a trailer while social media is already at its loudest fits the plan perfectly. That said, this is Rockstar, so a random Tuesday with zero warning is always on the table.' },
      { type: 'h2', text: 'The clue worth knowing' },
      { type: 'p', text: 'Fans spotted fresh artwork on Rockstar’ site showing Jason and Lucia, with a filename reading Lucia and Jason 3, matching the numbering used on the previous two trailer thumbnails. Circumstantial, but the community has run with it.' },
      { type: 'h2', text: 'Why this one matters more' },
      { type: 'p', text: 'Rockstar is taking up to £89.99 from millions of people who have not seen a single second of actual gameplay. Both existing trailers are cutscenes and scenery, gorgeous but not mechanics. Trailer 3 is where Rockstar finally has to show driving, shooting and the HUD. Whenever it lands, it will be the biggest gaming moment of the year.' },
      { type: 'p', text: 'Sources: GTA BOOM, Forbes and GameSpot coverage, late June to early July 2026.' },
    ],
  },
  {
    kind: 'article',
    slug: 'sound-of-leonida',
    title: 'The sound of Leonida: every song in the GTA 6 trailers',
    kicker: 'Culture',
    category: 'news',
    excerpt: 'A GTA radio dial is half the reason people fall in love with these worlds. Here is every track Rockstar has used so far, and what it hints at.',
    updatedAt: '2026-07-03',
    readingMins: 2,
    gradient: 'linear-gradient(150deg,#1FE5D6,#FF2E88)',
    motif: 'cassette',
    heroImage: { src: '/media/gtavi-vc-neon.jpg', alt: 'Vice City after dark', credit: 'Rockstar Games' },
    gallery: [{ src: '/media/gtavi-leonida-keys.jpg', alt: 'The Leonida Keys, all sun and salt water', credit: 'Rockstar Games' }],
    body: [
      { type: 'p', text: 'Rockstar sells its cities through music as much as visuals, and the GTA 6 trailers have been careful about every song choice. Here is the running list.' },
      { type: 'h2', text: 'Trailer 1, December 2023' },
      { type: 'p', text: 'The reveal leaned on Tom Petty’ Love Is a Long Road, a wistful, wide-open choice that set the tone.' },
      { type: 'h2', text: 'Trailer 2, May 2025' },
      { type: 'p', text: 'The second trailer went deeper into the Vice City mood with the Pointer Sisters’ Hot Together, which Spotify reported jumping more than 180,000 per cent in plays week on week. Around it sat Wang Chung’ Everybody Have Fun Tonight, Child Support by Zenglen, Talkin’ to Myself Again by Tammy Wynette, and Thunder Island by Jay Ferguson. That is 80s pop, Haitian sound, classic country and yacht rock in one trailer, which maps neatly onto Leonida’ melting-pot setting.' },
      { type: 'p', text: 'Fans also clocked what sounds like Joan Jett’ I Love Rock ’n’ Roll under the trailer’ Ammu-Nation advert, though the exact version is unconfirmed, so it stays off the list until it is.' },
      { type: 'h2', text: 'What it hints at for the radio' },
      { type: 'p', text: 'Vice City in the 80s gave us one of the most beloved radio line-ups in gaming. This is a modern-day Vice City, so the smart expectation is a blend: a nostalgic 80s station or two nodding to the original, alongside contemporary hip-hop, Latin and pop reflecting the city as it is now. Rockstar has not confirmed the stations, so treat that as informed guesswork until the tracklist is official.' },
      { type: 'p', text: 'Sources: official trailer credits, Spotify’ post-trailer figures, and reporting on the Trailer 2 selections, 2025 to 2026.' },
    ],
  },
  {
    kind: 'article',
    slug: 'vercetti-estate',
    title: 'The Vercetti Estate is back: GTA 6’ Vice City callbacks',
    kicker: 'Analysis',
    category: 'news',
    excerpt: 'Buried in the Ultimate Edition detail is a name that stopped longtime fans cold. Here is what is confirmed, and what is hopeful theorising.',
    updatedAt: '2026-07-03',
    readingMins: 2,
    gradient: 'linear-gradient(150deg,#FF2E88,#FFC83D)',
    motif: 'palms',
    heroImage: { src: '/media/gtavi-vc-postcard.jpg', alt: 'Vice City, four decades on from the original', credit: 'Rockstar Games' },
    gallery: [{ src: '/media/gtavi-vc-estate.jpg', alt: 'Modern Vice City, where the Vercetti name resurfaces', credit: 'Rockstar Games' }],
    body: [
      { type: 'p', text: 'Among the pre-order and Ultimate Edition details, one line jumped out: the Vercetti Estate, named in Rockstar’ own copy. If that name means nothing to you, it means everything to anyone who played the original.' },
      { type: 'h2', text: 'What is confirmed' },
      { type: 'p', text: 'Tommy Vercetti was the player character in 2002’ Grand Theft Auto: Vice City, set in 1986, and by the end of that game he ran the city. In the Ultimate Edition blurb, Rockstar describes the Hawk and Little Morgan Revolvers as sourced from the Vercetti Estate, found at Ammu-Nation stores as Jason and Lucia’ story progresses. That is a genuine, official nod, tucked into a weapon description rather than a trailer. The Vintage Vice City Pack, included with every pre-order before 20 November and with boxed copies while stocks last, also hands you a tropical weapon pattern channelling the original kingpin’ palm-tree shirt. The callbacks are real and deliberate.' },
      { type: 'h2', text: 'What is not confirmed' },
      { type: 'p', text: 'Whether the estate itself is somewhere you can actually visit is not confirmed. Sourced from is flavour text until Rockstar shows the building. Whether Tommy appears, is referenced, or has any story role is pure speculation. Modern GTA 6 sits in the same continuity as GTA 5, roughly 40 in-game years after the original Vice City, so anything from a museum-piece mansion to a full easter-egg trail is possible. Rockstar has said nothing. Enjoy the theories, but do not treat them as fact.' },
      { type: 'p', text: 'Sources: Rockstar’ official Ultimate Edition and Vintage Vice City Pack descriptions, June 2026, and the original GTA Vice City for the Tommy Vercetti background.' },
    ],
  },

  // ------------------------------------------------------------------
  // THE RUMOUR MILL: explicitly unconfirmed. Never mixed with the facts.
  // ------------------------------------------------------------------
  {
    kind: 'article',
    slug: 'will-gta6-come-to-pc',
    title: 'The PC version: every signal, zero announcements',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'History says a PC release is close to inevitable. Rockstar has announced nothing. Here is the honest state of it.',
    updatedAt: '2026-07-02',
    readingMins: 5,
    isRumour: true,
    credibility: 4,
    gradient: 'linear-gradient(150deg,#FF9E45,#8A4FFF)',
    motif: 'pc',
    heroImage: { src: '/media/gtavi-vc-night-2.jpg', alt: 'Vice City at night', credit: 'Rockstar Games' },
    body: [
      { type: 'p', text: 'This is a Rumour Mill piece: nothing below is confirmed unless explicitly marked as such.' },
      { type: 'h2', text: 'The claim' },
      { type: 'p', text: 'That GTA 6 comes to PC well after the console launch. The window doing the rounds is 2027 to 2028, echoing how Rockstar has handled every recent release.' },
      { type: 'h2', text: 'Where it comes from' },
      { type: 'p', text: 'Precedent, mostly, and it is heavy: GTA 5 reached PC roughly eighteen months after consoles, and Red Dead Redemption 2 took about a year. Industry analysts have publicly projected a similar gap this time, and PC-focused outlets read every Rockstar launcher update as a tea leaf.' },
      { type: 'h2', text: 'What is actually confirmed' },
      { type: 'p', text: 'The game launches on PS5 and Xbox Series X|S on 19 November 2026, and that is the entire list. No announced PC version, no date, no price, no system requirements. Anyone presenting PC specs as fact is guessing, and you should treat their other claims accordingly.' },
      { type: 'h2', text: 'Our heat rating: 4/5' },
      { type: 'p', text: 'High, but read what it means. On precedent alone, a PC version existing eventually is very likely. Confidence in any particular date is close to zero. Do not build or buy a rig around a launch nobody has announced.' },
    ],
  },
  {
    kind: 'article',
    slug: 'official-companion-app-rumour',
    title: 'Is Rockstar building an official companion app?',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'Job listings, precedent from iFruit and RDR2, and fan theories about the in-game social feed. What the signals amount to.',
    updatedAt: '2026-07-02',
    readingMins: 5,
    isRumour: true,
    credibility: 3,
    gradient: 'linear-gradient(150deg,#1FE5D6,#FF2E88)',
    motif: 'phone',
    heroImage: { src: '/media/gtavi-real-dimez.jpg', alt: 'Real Dimez', credit: 'Rockstar Games' },
    body: [
      { type: 'p', text: 'This is a Rumour Mill piece: nothing below is confirmed unless explicitly marked as such.' },
      { type: 'h2', text: 'The claim' },
      { type: 'p', text: 'That Rockstar is building an official GTA 6 companion app for phones. Fan theories run from a real-world version of the game’s in-world social feed to remote character and vehicle management.' },
      { type: 'h2', text: 'Where it comes from' },
      { type: 'p', text: 'Job listings, chiefly: mobile engineer roles spotted on Rockstar’s careers site in mid-2025, at a studio believed to be leading GTA 6 development. Add the precedent (GTA 5 shipped with the iFruit app, Red Dead Redemption 2 had a full companion app with a live map) and the trailers’ heavy emphasis on in-world social media, and the theory writes itself.' },
      { type: 'h2', text: 'What is actually confirmed' },
      { type: 'p', text: 'Nothing. Rockstar has announced no app of any kind. Job adverts signal hiring intent, not products. The roles could serve anything in the company’s portfolio.' },
      { type: 'h2', text: 'Our heat rating: 3/5' },
      { type: 'p', text: 'Credible signals, strong precedent, zero confirmation. We would not be surprised either way, which is exactly what a three means.' },
    ],
  },
  {
    kind: 'article',
    slug: 'gta-online-2-whispers',
    title: 'GTA Online 2: what the whispers actually say',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'Rockstar calls launch a “single-player experience” with online to follow. Everything beyond that sentence is speculation, collected here.',
    updatedAt: '2026-07-02',
    readingMins: 6,
    isRumour: true,
    credibility: 3,
    gradient: 'linear-gradient(150deg,#8A4FFF,#1FE5D6)',
    motif: 'globe',
    heroImage: { src: '/media/gtavi-keys-party.jpg', alt: 'Boat party in the Leonida Keys', credit: 'Rockstar Games' },
    body: [
      { type: 'p', text: 'This is a Rumour Mill piece: nothing below is confirmed unless explicitly marked as such.' },
      { type: 'h2', text: 'The claim' },
      { type: 'p', text: 'That the online mode arrives as its own launch some time after the campaign. A true successor to GTA Online rather than a bolted-on mode, with open questions about its name, its structure, and whether anything carries over from the original.' },
      { type: 'h2', text: 'Where it comes from' },
      { type: 'p', text: 'Three places. Rockstar’s own launch language, “a single-player experience” with the online component to follow, which invites the staggered-launch reading. Reports of an Xbox file leak said to hint at the multiplayer mode’s structure. And precedent: GTA Online itself launched two weeks after GTA 5, then outgrew it.' },
      { type: 'h2', text: 'What is actually confirmed' },
      { type: 'p', text: 'Only the first part: Rockstar has said the launch is a single-player experience and that an online component follows. There is no confirmed name, date, structure, business model, or word on whether GTA Online progress or purchases carry over in any form.' },
      { type: 'h2', text: 'Our heat rating: 3/5' },
      { type: 'p', text: 'The staggered launch is more inference than rumour, since Rockstar’s own wording points that way. What the mode actually is remains unknown, leaked files included. Leaks describe files. They do not describe plans.' },
    ],
  },
  {
    kind: 'article',
    slug: 'sixty-fps-question',
    title: 'Will it run at 60fps? The performance question',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'The hope: a 60fps mode, at least on PS5 Pro. The loudest expert analysis points the other way. The honest state of play.',
    updatedAt: '2026-07-02',
    readingMins: 5,
    isRumour: true,
    credibility: 2,
    gradient: 'linear-gradient(150deg,#FF2E88,#FF9E45)',
    motif: 'controller',
    heroImage: { src: '/media/gtavi-kalaga-heli.jpg', alt: 'Helicopter over Mount Kalaga', credit: 'Rockstar Games' },
    body: [
      { type: 'p', text: 'This is a Rumour Mill piece: nothing below is confirmed unless explicitly marked as such.' },
      { type: 'h2', text: 'The claim' },
      { type: 'p', text: 'That GTA 6 ships with a 60fps performance mode. Or, in the more cautious version, that the PS5 Pro at least gets one.' },
      { type: 'h2', text: 'Where it comes from' },
      { type: 'p', text: 'Mostly hope and hardware discourse: the PS5 Pro’s marketing positioning, Sony’s “plays best on PS5” campaign for the game, and the community’s standard expectation of a fidelity/performance toggle in big releases.' },
      { type: 'h2', text: 'What is actually confirmed' },
      { type: 'p', text: 'Nothing about frame rates, resolution, or performance modes on any console. Notably, the loudest expert signal points the other way: Digital Foundry’s read of the June screenshot drop is that the stills are unlikely to represent real-time output on PS5 or Series X. Best case, PS5 Pro. And experts have been openly sceptical about 60fps even there. “Plays best on PS5” is a marketing line, not a spec sheet.' },
      { type: 'h2', text: 'Our heat rating: 2/5' },
      { type: 'p', text: 'Low. Not because the question is silly, but because the credible analysis currently leans against it and Rockstar has said nothing. A gameplay trailer with a stated capture platform would move this rating fast, in either direction.' },
    ],
  },
  {
    kind: 'article',
    slug: 'leonida-map-size',
    title: 'How big is Leonida? The mapping project’s best guess',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'The community has been triangulating trailers and screenshots for two years. The estimates are clever. They are still estimates.',
    updatedAt: '2026-07-02',
    readingMins: 5,
    isRumour: true,
    credibility: 2,
    gradient: 'linear-gradient(150deg,#35E27C,#1FE5D6 55%,#8A4FFF)',
    motif: 'map',
    heroImage: { src: '/media/gtavi-vc-aerial.jpg', alt: 'Vice City from above', credit: 'Rockstar Games' },
    body: [
      { type: 'p', text: 'This is a Rumour Mill piece: nothing below is confirmed unless explicitly marked as such.' },
      { type: 'h2', text: 'The claim' },
      { type: 'p', text: 'That Leonida is roughly twice the size of GTA 5’s map, comfortably the biggest world Rockstar has ever built. The figure gets repeated so often it is close to being treated as fact.' },
      { type: 'h2', text: 'Where it comes from' },
      { type: 'p', text: 'The community mapping project: an impressively disciplined effort that triangulates every trailer frame and screenshot against known landmarks, road signage and coastline shapes to sketch the state’s outline. The method is genuinely clever, and its Vice City work has held up well against each new official release.' },
      { type: 'h2', text: 'What is actually confirmed' },
      { type: 'p', text: 'The setting: the state of Leonida, centred on a modern Vice City, with official material showing keys, swampland and countryside well beyond the city. Rockstar has published no dimensions, no comparison, and no map.' },
      { type: 'h2', text: 'Our heat rating: 2/5' },
      { type: 'p', text: 'The rating reflects the specific claim, not the project. “Bigger than GTA 5” is very probable. “Roughly twice the size” carries error bars that marketing footage cannot honestly close. We will map the real thing with the community from day one. That is rather the point of this site.' },
    ],
  },

  {
    kind: 'article',
    slug: 'third-delay',
    title: 'Could GTA 6 slip a third time?',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'Every few weeks someone insists GTA 6 is heading to 2027. Here is the case, and why the evidence points the other way.',
    updatedAt: '2026-07-03',
    readingMins: 2,
    isRumour: true,
    credibility: 2,
    gradient: 'linear-gradient(150deg,#FFC83D,#FF2E88)',
    motif: 'question',
    heroImage: { src: '/media/gtavi-cover-art.jpg', alt: 'The official GTA 6 cover art', credit: 'Rockstar Games' },
    gallery: [{ src: '/media/gtavi-jason-lucia-a.jpg', alt: 'The pair Rockstar insists you will be playing this November', credit: 'Rockstar Games' }],
    body: [
      { type: 'p', text: 'The rumour is simple. Rockstar has delayed this game twice already, from a 2025 window to May 2026 to 19 November 2026, and the studio has a real history of delaying big titles more than once. So a third slip cannot be ruled out. That is the whole foundation of the cope discourse, and it is not nothing.' },
      { type: 'h2', text: 'Why it probably will not happen' },
      { type: 'p', text: 'The counter-evidence is strong. Zelnick has repeatedly reiterated the 19 November date to investors, and Take-Two has staked a record revenue forecast, in the region of 8 billion dollars for the year, on it holding. Reporter Jason Schreier, who called earlier delays correctly, has said people at Rockstar consider November more solid than the previous dates. And the tell that usually gets missed: rival publishers have been shoving their own games out of GTA 6’ path into September or 2027. Nobody rearranges half an industry around a date they expect to move.' },
      { type: 'h2', text: 'The verdict' },
      { type: 'p', text: 'Never say never with Rockstar, but a third delay looks unlikely, and this stays firmly in the rumour column until anything official says otherwise.' },
      { type: 'p', text: 'Sources: ScreenRant, Variety, and Jason Schreier’ podcast comments, 2026.' },
    ],
  },
  {
    kind: 'article',
    slug: 'catching-leakers',
    title: 'Is Rockstar feeding its own staff fake info to catch leakers?',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'One of the more fascinating GTA 6 rumours is not about the game at all. It is about how far Rockstar will go to stop it leaking.',
    updatedAt: '2026-07-03',
    readingMins: 2,
    isRumour: true,
    credibility: 3,
    gradient: 'linear-gradient(150deg,#8A4FFF,#1FE5D6)',
    motif: 'signal',
    heroImage: { src: '/media/gtavi-cal-hampton.jpg', alt: 'Cal Hampton, GTA 6’ resident conspiracy theorist', credit: 'Rockstar Games' },
    gallery: [{ src: '/media/gtavi-gellhorn.jpg', alt: 'Port Gellhorn, one of Leonida’ quieter corners', credit: 'Rockstar Games' }],
    body: [
      { type: 'p', text: 'This one is reported rather than confirmed, so Heat sits in the middle. The claim, circulating in coverage of Rockstar’ secrecy, is that the studio has at times planted false information within internal teams, so that if a specific detail leaks online, they can trace which group it came from. Think of it as a mole hunt, closer to a spy-agency playbook than a game studio.' },
      { type: 'h2', text: 'Why it is believable' },
      { type: 'p', text: 'The context makes it plausible. GTA 6 suffered one of the biggest leaks in gaming history in September 2022, when footage from unfinished builds spread everywhere. And in late 2025, Rockstar dismissed a number of employees, citing the discussion and distribution of confidential information, a move that drew criticism from a union. A company burned that badly, protecting a product this valuable, taking hard measures to plug leaks is entirely in character.' },
      { type: 'h2', text: 'The caveat' },
      { type: 'p', text: 'The specific fake-info tactic is second-hand reporting, not something Rockstar has confirmed. File it as a compelling rumour, not a fact.' },
      { type: 'p', text: 'Sources: reporting on Rockstar’ anti-leak measures and the 2025 dismissals, 2026.' },
    ],
  },
  {
    kind: 'article',
    slug: 'collectors-edition-rumour',
    title: 'A collector’ edition and PS5 bundles? What the rumours point to',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'The Standard and Ultimate editions are confirmed. The rumour mill says that might not be the whole line-up.',
    updatedAt: '2026-07-03',
    readingMins: 2,
    isRumour: true,
    credibility: 3,
    gradient: 'linear-gradient(150deg,#FFC83D,#8A4FFF)',
    motif: 'money',
    heroImage: { src: '/media/gtavi-ultimate-edition.jpg', alt: 'Some of the GTA 6 Ultimate Edition content', credit: 'Rockstar Games' },
    gallery: [{ src: '/media/gtavi-cheetah.jpg', alt: 'Premium Ultimate content like the Grotti Cheetah hints at how much a collector’ set could carry', credit: 'Rockstar Games' }],
    body: [
      { type: 'p', text: 'Rockstar has officially confirmed two editions: Standard and Ultimate. The persistent rumour, though, is that the wider commercial line-up is bigger than that. Reports have pointed to several physical and digital variants, a couple of PlayStation console bundles, and a single, pricier collector’ edition sitting above Ultimate.' },
      { type: 'h2', text: 'Why it is plausible' },
      { type: 'p', text: 'Almost every major launch of this size ships a physical collector’ edition, often with a statue, steelbook or map, and console bundles are a standard play, especially given the PlayStation marketing tie-in that is now visible in the ads themselves. It would genuinely be a surprise if none of this materialised.' },
      { type: 'h2', text: 'The caveat' },
      { type: 'p', text: 'None of the collector’ edition or bundle detail is officially confirmed. If a physical set is coming, expect Rockstar to announce it in its own window, possibly alongside a trailer. Until then, do not pre-order anything claiming to be one.' },
      { type: 'p', text: 'Sources: GamingBible and aggregated pre-order and retail-listing reporting, May to June 2026.' },
    ],
  },
];
