import type { Category, Guide, Article } from '@/lib/types';

export const MOCK_CATEGORIES: Category[] = [
  { slug: 'all', name: 'All' },
  { slug: 'beginner', name: 'Beginner' },
  { slug: 'money', name: 'Money' },
  { slug: 'collectibles', name: 'Collectibles' },
  { slug: 'missions', name: 'Missions' },
  { slug: 'vehicles', name: 'Vehicles' },
  { slug: 'map', name: 'Map' },
  { slug: 'news', name: 'News' },
];

const G = (s: string) => s; // gradient passthrough for readability

export const MOCK_GUIDES: Guide[] = [
  // Deliberately empty pre-launch. Nothing publishes as a guide before it can
  // be verified in-game — /guides carries the Guides Desk roadmap instead.
  // The full guide system (cards, tracker chips, articles) is built and waiting.
];

export const MOCK_ARTICLES: Article[] = [
  // ------------------------------------------------------------------
  // LATEST NEWS — verified. Facts strictly separated from rumour.
  // ------------------------------------------------------------------
  {
    kind: 'article',
    slug: 'everything-confirmed',
    title: 'GTA 6: Everything confirmed so far',
    kicker: 'The big read',
    category: 'news',
    excerpt: 'The running list of what Rockstar has officially confirmed about Grand Theft Auto VI — kept strictly separate from the rumours.',
    updatedAt: '2026-07-02',
    readingMins: 8,
    gradient: 'linear-gradient(150deg,#FF2E88,#8A4FFF 55%,#1FE5D6)',
    motif: 'skyline',
    body: [
      { type: 'p', text: 'This is our living roundup of what is officially confirmed about Grand Theft Auto VI. Confirmed facts are kept strictly separate from rumour — anything unconfirmed lives in the Rumour Mill, clearly labelled. Last full check: 2 July 2026.' },
      { type: 'h2', text: 'Confirmed' },
      { type: 'ul', items: [
        'Release date: Thursday 19 November 2026, on PS5 and Xbox Series X|S.',
        'Dual protagonists: Jason Duval and Lucia Caminos — Lucia is the series\u2019 first playable female lead of the modern era.',
        'Setting: the state of Leonida, centred on a modern Vice City.',
        'Editions: Standard (\u00a369.99) and Ultimate (\u00a389.99). Standard owners can buy the Ultimate upgrade at any time.',
        'Every pre-order before 20 November gets the Vintage Vice City Pack; digital pre-orders also include one month of GTA+, redeemable within 180 days.',
        'Pre-loading opens 12 November. Boxed copies contain a download code rather than a disc, and go on sale from 12 November.',
        'The official cover art was revealed in June, and Rockstar published its biggest screenshot drop yet — more than 60 images — alongside pre-orders opening on 25 June.',
        'Rockstar describes the launch as a single-player experience, with the online component to follow.',
      ] },
      { type: 'h2', text: 'Not yet confirmed' },
      { type: 'ul', items: [
        'A PC version — no announcement, no date, no specs. Anything you see quoted is a guess.',
        'The online mode\u2019s name, structure, or timing beyond \u201cto follow\u201d.',
        'Performance modes and frame rates on any console.',
        'The install size, and exact launch unlock times by region.',
      ] },
      { type: 'p', text: 'Sources: Rockstar Newswire announcements, 18\u201325 June 2026, and the official Grand Theft Auto VI site.' },
    ],
  },
  {
    kind: 'article',
    slug: 'which-edition-to-preorder',
    title: 'Which edition should you pre-order? (UK)',
    kicker: 'Buying',
    category: 'news',
    excerpt: 'Standard vs Ultimate, boxed vs digital, and where to pre-order in the UK — with the pricing that actually matters.',
    updatedAt: '2026-07-02',
    readingMins: 7,
    isNew: true,
    gradient: 'linear-gradient(150deg,#1FE5D6,#8A4FFF)',
    motif: 'money',
    body: [
      { type: 'p', text: 'Two editions, a boxed option that is really a download code, and a handful of UK retailers. Here is how to decide.' },
      { type: 'h2', text: 'The editions' },
      { type: 'ul', items: [
        'Standard — \u00a369.99. The base game plus the Vintage Vice City Pack pre-order bonus.',
        'Ultimate — \u00a389.99. Adds an exclusive collection for the story: premium vehicles including the \u201995 Grotti Cheetah, two exclusive vehicle mod shops, a Classic Car Collection commission, a signature salon for Jason\u2019s facial hair and Lucia\u2019s nails, the Stock 305 clothing store, and exclusive weapon variants including the Hawk & Little Morgan revolver.',
      ] },
      { type: 'p', text: 'One detail widely misreported elsewhere: the free month of GTA+ is not an Ultimate Edition perk. It comes with any digital pre-order, either edition, and must be redeemed within 180 days.' },
      { type: 'p', text: 'You can buy Standard now and upgrade to Ultimate later at any time, so there is no rush to the pricier edition if you are unsure.' },
      { type: 'h2', text: 'Boxed or digital?' },
      { type: 'ul', items: [
        'The boxed version contains a download code — there is no disc. It ships from 12 November so you can redeem and pre-load before launch.',
        'Digital pre-orders pre-load from 12 November and include the month of GTA+.',
      ] },
      { type: 'h2', text: 'One honest note on the Ultimate Edition' },
      { type: 'p', text: 'Locking entire in-game shops behind the \u00a320 upgrade has drawn real criticism from the community — it is the first time whole locations, rather than items, sit behind an edition paywall in the series. Rockstar has confirmed that nothing in the Ultimate Edition is required to play or complete the game. Our straight read: if the customisation extras excite you, the upgrade path means you can decide after launch rather than at pre-order.' },
      { type: 'p', text: 'Sources: Rockstar Newswire edition announcement, 24 June 2026; UK storefront pricing confirmed 25 June 2026.' },
    ],
  },
  {
    kind: 'article',
    slug: 'no-disc-in-the-box',
    title: 'No disc in the box: the physical edition, explained',
    kicker: 'Hardware',
    category: 'news',
    excerpt: 'Boxed GTA 6 ships with a download code, not a disc. What is actually in the box, why Rockstar says it is doing it, and what it means for you.',
    updatedAt: '2026-07-02',
    readingMins: 5,
    isNew: true,
    gradient: 'linear-gradient(150deg,#FF9E45,#FF2E88 60%,#8A4FFF)',
    motif: 'disc',
    body: [
      { type: 'p', text: 'Confirmed with the edition reveal on 24 June: the boxed, physical version of Grand Theft Auto VI does not contain a game disc. Inside the retail case is a one-time download code.' },
      { type: 'h2', text: 'What is actually in the box' },
      { type: 'ul', items: [
        'A retail case and a code that unlocks a full digital download — the entire game installs to your console\u2019s storage.',
        'Boxed copies go on sale from 12 November, a week early, specifically so buyers can redeem the code and pre-load before launch night.',
        'There is no disc-based play, and no lending or reselling the game once the code is redeemed.',
      ] },
      { type: 'h2', text: 'Why Rockstar says it is doing this' },
      { type: 'p', text: 'The stated reason is pre-loading: with a code in every box, every player can have the game installed and ready at the moment of launch, rather than installing from a disc on the night. It also means the disc-drive-less PS5 and Series S are on exactly the same footing as every other console — Sony even re-shot a pre-order advert around a digital-edition PS5 after the announcement.' },
      { type: 'h2', text: 'What it means for you' },
      { type: 'ul', items: [
        'You need the storage free and a connection capable of a very large download — plan for that before 12 November.',
        'Collectors get a box for the shelf; the traditional second-hand and lending market for this game is effectively gone.',
        'If launch-night play matters to you, pre-load from 12 November whichever route you buy.',
      ] },
      { type: 'p', text: 'Sources: Rockstar Newswire pre-order announcement, 24 June 2026.' },
    ],
  },
  {
    kind: 'article',
    slug: 'vintage-vice-city-pack',
    title: 'Everything in the Vintage Vice City Pack',
    kicker: 'Pre-order bonus',
    category: 'news',
    excerpt: 'The pre-order bonus every buyer gets before 20 November — the \u201955 sedan, the Ocean Beach garage, and the retro wardrobe, itemised.',
    updatedAt: '2026-07-02',
    readingMins: 4,
    gradient: 'linear-gradient(150deg,#FFC83D,#FF9E45 55%,#FF2E88)',
    motif: 'cassette',
    body: [
      { type: 'p', text: 'The Vintage Vice City Pack is the pre-order bonus, and it is tied to ordering early rather than spending more: anyone who pre-orders before 20 November gets it, on either edition.' },
      { type: 'h2', text: 'What is in it' },
      { type: 'ul', items: [
        'The \u201955 Vapid Stanier — a classic sedan built for cruising Shore Drive.',
        'The Shore Court personal garage, a stone\u2019s throw from the sands of Ocean Beach.',
        'Retro outfits and hairstyles for both Jason and Lucia.',
        'A vintage weapon pattern echoing the excess of the old Vice City era.',
      ] },
      { type: 'h2', text: 'The extra for digital buyers' },
      { type: 'p', text: 'Pre-order digitally — either edition — and you also get one month of GTA+, which must be redeemed within 180 days of launch.' },
      { type: 'p', text: 'Worth being clear-eyed: this is cosmetic, nostalgic flavour rather than anything that changes how the game plays. A lovely callback for series veterans; not a reason to pre-order if you were otherwise waiting for reviews.' },
      { type: 'p', text: 'Sources: Rockstar Newswire edition announcement, 24 June 2026.' },
    ],
  },
  {
    kind: 'article',
    slug: 'screenshot-drop-what-it-confirms',
    title: 'The 60-screenshot drop: what it actually confirms',
    kicker: 'Analysis',
    category: 'news',
    excerpt: 'Rockstar\u2019s biggest image release yet landed with pre-orders. Here is what the stills genuinely confirm — and the one caveat worth keeping.',
    updatedAt: '2026-07-02',
    readingMins: 6,
    gradient: 'linear-gradient(150deg,#FF2E88,#FF9E45 60%,#FFC83D)',
    motif: 'palms',
    // To run a credited official screenshot instead of the generated art,
    // drop the file in web/public/media/ and uncomment:
    // heroImage: { src: '/media/gtavi-screenshot-01.jpg', alt: 'Vice City at dusk', credit: 'Rockstar Games' },
    body: [
      { type: 'p', text: 'Alongside pre-orders opening on 25 June, Rockstar published its biggest still-image release for the game so far — more than 60 screenshots, 51 of them on the official media page, largely built around the Ultimate Edition and the Vintage Vice City Pack.' },
      { type: 'h2', text: 'What the images genuinely confirm' },
      { type: 'ul', items: [
        'Character customisation runs far deeper than GTA 5 — the stills show Jason and Lucia across dozens of hairstyles, outfits, tattoos and nail designs.',
        'Named in-world businesses, including Sara\u2019s Unisex Salon and the Electric Fang tattoo shop.',
        'A spread of new vehicles and boats, plus vehicle and boat customisation.',
        'A deliberately \u201980s-leaning retro aesthetic across the pre-order marketing — a clear nod to the original Vice City era.',
      ] },
      { type: 'h2', text: 'The caveat worth keeping' },
      { type: 'p', text: 'These are in-engine 4K stills published for marketing. Digital Foundry has publicly questioned whether they represent real-time output on launch consoles, noting the image quality suggests settings beyond what PS5 or Series X are likely to render live. Until Rockstar ships a gameplay trailer with a stated capture platform, treat the polish as marketing-grade rather than a performance promise.' },
      { type: 'p', text: 'Anything from the gallery that hardens into confirmed fact gets folded into our Everything Confirmed roundup; the frame-rate question lives where it belongs, in the Rumour Mill.' },
      { type: 'p', text: 'Sources: Rockstar Games media page, 24\u201325 June 2026; Digital Foundry commentary, June 2026.' },
    ],
  },

  // ------------------------------------------------------------------
  // THE RUMOUR MILL — explicitly unconfirmed. Never mixed with the facts.
  // ------------------------------------------------------------------
  {
    kind: 'article',
    slug: 'will-gta6-come-to-pc',
    title: 'The PC version: every signal, zero announcements',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'History says a PC release is close to inevitable. Rockstar has announced nothing. Here is the honest state of it.',
    updatedAt: '2026-07-02',
    readingMins: 5,
    isRumour: true,
    credibility: 4,
    gradient: 'linear-gradient(150deg,#FF9E45,#8A4FFF)',
    motif: 'pc',
    body: [
      { type: 'p', text: 'This is a Rumour Mill piece: nothing below is confirmed unless explicitly marked as such.' },
      { type: 'h2', text: 'The claim' },
      { type: 'p', text: 'That GTA 6 comes to PC well after the console launch — the expectation circulating most is a 2027\u201328 window, echoing how Rockstar has handled every recent release.' },
      { type: 'h2', text: 'Where it comes from' },
      { type: 'p', text: 'Precedent, mostly, and it is heavy: GTA 5 reached PC roughly eighteen months after consoles, and Red Dead Redemption 2 took about a year. Industry analysts have publicly projected a similar gap this time, and PC-focused outlets read every Rockstar launcher update as a tea leaf.' },
      { type: 'h2', text: 'What is actually confirmed' },
      { type: 'p', text: 'The game launches on PS5 and Xbox Series X|S on 19 November 2026 — and that is the entire list. There is no announced PC version, no date, no price, and no system requirements. Anyone presenting PC specs as fact is guessing, and you should treat their other claims accordingly.' },
      { type: 'h2', text: 'Our heat rating: 4/5' },
      { type: 'p', text: 'High — but read what it means. We rate the likelihood a PC version exists eventually as very high on precedent alone; confidence in any particular date is close to zero. Do not build or buy a rig around a launch nobody has announced.' },
    ],
  },
  {
    kind: 'article',
    slug: 'official-companion-app-rumour',
    title: 'Is Rockstar building an official companion app?',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'Job listings, precedent from iFruit and RDR2, and fan theories about the in-game social feed. What the signals amount to.',
    updatedAt: '2026-07-02',
    readingMins: 5,
    isRumour: true,
    credibility: 3,
    gradient: 'linear-gradient(150deg,#1FE5D6,#FF2E88)',
    motif: 'phone',
    body: [
      { type: 'p', text: 'This is a Rumour Mill piece: nothing below is confirmed unless explicitly marked as such.' },
      { type: 'h2', text: 'The claim' },
      { type: 'p', text: 'That Rockstar is developing an official GTA 6 companion app for phones — with fan theories ranging from a real-world version of the game\u2019s in-world social feed to remote character and vehicle management.' },
      { type: 'h2', text: 'Where it comes from' },
      { type: 'p', text: 'Job listings, chiefly: mobile engineer roles spotted on Rockstar\u2019s careers site in mid-2025, at a studio believed to be leading GTA 6 development. Add the precedent — GTA 5 shipped with the iFruit app and Red Dead Redemption 2 had a full companion app with a live map — and the trailers\u2019 heavy emphasis on in-world social media, and the theory writes itself.' },
      { type: 'h2', text: 'What is actually confirmed' },
      { type: 'p', text: 'Nothing. Rockstar has announced no app of any kind. Job adverts signal hiring intent, not products — the roles could serve anything in the company\u2019s portfolio.' },
      { type: 'h2', text: 'Our heat rating: 3/5' },
      { type: 'p', text: 'Credible signals, strong precedent, zero confirmation. We would not be surprised either way — which is exactly what a three means.' },
    ],
  },
  {
    kind: 'article',
    slug: 'gta-online-2-whispers',
    title: 'GTA Online 2: what the whispers actually say',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'Rockstar calls launch a \u201csingle-player experience\u201d with online to follow. Everything beyond that sentence is speculation — collected here.',
    updatedAt: '2026-07-02',
    readingMins: 6,
    isRumour: true,
    credibility: 3,
    gradient: 'linear-gradient(150deg,#8A4FFF,#1FE5D6)',
    motif: 'globe',
    body: [
      { type: 'p', text: 'This is a Rumour Mill piece: nothing below is confirmed unless explicitly marked as such.' },
      { type: 'h2', text: 'The claim' },
      { type: 'p', text: 'That the online mode arrives as a separate launch some time after the campaign — a true successor to GTA Online rather than a bolted-on mode — with open questions about its name, its structure, and whether anything carries over from the original.' },
      { type: 'h2', text: 'Where it comes from' },
      { type: 'p', text: 'Three places. Rockstar\u2019s own launch language — \u201ca single-player experience\u201d with the online component to follow — which invites the staggered-launch reading. Reports of an Xbox file leak said to hint at the multiplayer mode\u2019s structure. And precedent: GTA Online itself launched two weeks after GTA 5, then outgrew it.' },
      { type: 'h2', text: 'What is actually confirmed' },
      { type: 'p', text: 'Only the first part: Rockstar has said the launch is a single-player experience and that an online component follows. There is no confirmed name, date, structure, business model, or word on whether GTA Online progress or purchases carry over in any form.' },
      { type: 'h2', text: 'Our heat rating: 3/5' },
      { type: 'p', text: 'The staggered launch is more inference than rumour — Rockstar\u2019s wording points that way. Everything about what the mode actually is remains genuinely unknown, leaked files included. Leaks describe files; they do not describe plans.' },
    ],
  },
  {
    kind: 'article',
    slug: 'sixty-fps-question',
    title: 'Will it run at 60fps? The performance question',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'The hope: a 60fps mode, at least on PS5 Pro. The loudest expert analysis points the other way. The honest state of play.',
    updatedAt: '2026-07-02',
    readingMins: 5,
    isRumour: true,
    credibility: 2,
    gradient: 'linear-gradient(150deg,#FF2E88,#FF9E45)',
    motif: 'controller',
    body: [
      { type: 'p', text: 'This is a Rumour Mill piece: nothing below is confirmed unless explicitly marked as such.' },
      { type: 'h2', text: 'The claim' },
      { type: 'p', text: 'That GTA 6 ships with a 60fps performance mode — or, in the more cautious version, that the PS5 Pro at least gets one.' },
      { type: 'h2', text: 'Where it comes from' },
      { type: 'p', text: 'Mostly hope and hardware discourse: the PS5 Pro\u2019s marketing positioning, Sony\u2019s \u201cplays best on PS5\u201d campaign for the game, and the community\u2019s standard expectation of a fidelity/performance toggle in big releases.' },
      { type: 'h2', text: 'What is actually confirmed' },
      { type: 'p', text: 'Nothing about frame rates, resolution, or performance modes on any console. Notably, the loudest expert signal points the other way: Digital Foundry\u2019s read of the June screenshot drop is that the stills are unlikely to represent real-time output on PS5 or Series X — best case, PS5 Pro — and experts have been openly sceptical about 60fps even there. \u201cPlays best on PS5\u201d is a marketing line, not a spec sheet.' },
      { type: 'h2', text: 'Our heat rating: 2/5' },
      { type: 'p', text: 'Low. Not because the question is silly — because the credible analysis currently leans against, and Rockstar has said nothing. A gameplay trailer with a stated capture platform would move this rating fast, in either direction.' },
    ],
  },
  {
    kind: 'article',
    slug: 'leonida-map-size',
    title: 'How big is Leonida? The mapping project\u2019s best guess',
    kicker: 'Rumour Mill',
    category: 'rumour',
    excerpt: 'The community has been triangulating trailers and screenshots for two years. The estimates are clever. They are still estimates.',
    updatedAt: '2026-07-02',
    readingMins: 5,
    isRumour: true,
    credibility: 2,
    gradient: 'linear-gradient(150deg,#35E27C,#1FE5D6 55%,#8A4FFF)',
    motif: 'map',
    body: [
      { type: 'p', text: 'This is a Rumour Mill piece: nothing below is confirmed unless explicitly marked as such.' },
      { type: 'h2', text: 'The claim' },
      { type: 'p', text: 'That Leonida is roughly twice the size of GTA 5\u2019s map — comfortably the biggest world Rockstar has built — with the figure repeated so often it is close to being treated as fact.' },
      { type: 'h2', text: 'Where it comes from' },
      { type: 'p', text: 'The community mapping project: an impressively disciplined effort that triangulates every trailer frame and screenshot against known landmarks, road signage and coastline shapes to sketch the state\u2019s outline. The method is genuinely clever, and its Vice City work has held up well against each new official release.' },
      { type: 'h2', text: 'What is actually confirmed' },
      { type: 'p', text: 'The setting: the state of Leonida, centred on a modern Vice City, with official material showing keys, swampland and countryside well beyond the city. Rockstar has published no dimensions, no comparison, and no map.' },
      { type: 'h2', text: 'Our heat rating: 2/5' },
      { type: 'p', text: 'The rating reflects the specific claim, not the project. \u201cBigger than GTA 5\u201d is very probable; \u201croughly twice the size\u201d carries error bars the method cannot honestly close from marketing footage alone. We will map the real thing with the community from day one — that is rather the point of this site.' },
    ],
  },
];
