import type { Category, Guide, Article } from '@/lib/types';

export const MOCK_CATEGORIES: Category[] = [
  { slug: 'all', name: 'All' },
  { slug: 'beginner', name: 'Beginner' },
  { slug: 'money', name: 'Money' },
  { slug: 'collectibles', name: 'Collectibles' },
  { slug: 'missions', name: 'Missions' },
  { slug: 'vehicles', name: 'Vehicles' },
  { slug: 'map', name: 'Map' },
  { slug: 'news', name: 'News' },
];

const G = (s: string) => s; // gradient passthrough for readability

export const MOCK_GUIDES: Guide[] = [
  {
    kind: 'guide',
    slug: 'your-first-ten-hours',
    title: 'Your first ten hours in Leonida',
    kicker: 'Beginner',
    category: 'beginner',
    excerpt: 'A spoiler-safe path through the opening: what to prioritise, what to ignore, and how not to waste your early money.',
    updatedAt: '2026-06-30',
    readingMins: 11,
    gradient: 'linear-gradient(150deg,#FF2E88,#8A4FFF 60%,#1FE5D6)',
    body: [
      { type: 'p', text: 'The opening hours of a Grand Theft Auto game set the tone for everything after, and Leonida is no different. This guide keeps things spoiler-safe while pointing you at the decisions that actually matter early on.' },
      { type: 'h2', text: 'Do these first' },
      { type: 'ul', items: ['Follow the story until the map opens up — it unlocks fast travel and key services.', 'Grab the free collectibles that sit on your critical path; do not detour for them yet.', 'Hold your cash. The tempting early purchases are rarely the ones worth making.'] },
      { type: 'p', text: 'Once the world is open, switch to the SixCentral tracker so your collectible and completion progress carries across every session.' },
    ],
    trackable: { label: 'Overall completion', slug: 'completion' },
  },
  {
    kind: 'guide',
    slug: 'fastest-money-methods',
    title: 'The fastest legit money methods at launch',
    kicker: 'Money',
    category: 'money',
    excerpt: 'No glitches, no exploits — the cleanest ways to build a bankroll in the early game, ranked by effort.',
    updatedAt: '2026-06-30',
    readingMins: 8,
    isNew: true,
    gradient: 'linear-gradient(150deg,#35E27C,#1FE5D6 60%,#8A4FFF)',
    body: [
      { type: 'p', text: 'Everyone wants a fast bankroll. These are legitimate, launch-day-safe methods — no glitches that get patched and no exploits that risk your save.' },
      { type: 'h2', text: 'Ranked by effort vs reward' },
      { type: 'ul', items: ['Story payouts — the reliable baseline; do not skip optional objectives.', 'Early businesses that pay back quickly (see our businesses guide).', 'Repeatable world activities once the map is open.'] },
    ],
  },
  {
    kind: 'guide',
    slug: 'all-hidden-package-locations',
    title: 'All hidden package locations & map',
    kicker: 'Collectibles',
    category: 'collectibles',
    excerpt: 'Every hidden package, plotted on our original interactive map, with your found/missing count synced to the tracker.',
    updatedAt: '2026-06-28',
    readingMins: 11,
    gradient: 'linear-gradient(150deg,#FF2E88,#FF9E45 60%,#FFC83D)',
    body: [
      { type: 'p', text: 'Hidden packages are the classic completionist grind. This guide plots every location on the SixCentral map — our own artwork, with community-verified pins.' },
      { type: 'h2', text: 'How to use this with the tracker' },
      { type: 'p', text: 'Open the companion app to see which packages you have left. The map shows verified pins for everyone and pending pins that the community is still confirming.' },
    ],
    trackable: { label: 'Hidden packages', slug: 'hidden-packages' },
  },
  {
    kind: 'guide',
    slug: 'full-completion-checklist',
    title: 'Full 100% completion checklist',
    kicker: '100%',
    category: 'collectibles',
    excerpt: 'Everything you need to hit 100% in Leonida, in a sensible order, with live progress from your tracker.',
    updatedAt: '2026-06-30',
    readingMins: 14,
    gradient: 'linear-gradient(150deg,#8A4FFF,#FF2E88 60%,#1FE5D6)',
    body: [
      { type: 'p', text: 'A complete, ordered checklist for 100% completion. Work top to bottom and your tracker keeps the running total.' },
    ],
    trackable: { label: 'Completion', slug: 'completion' },
  },
  {
    kind: 'guide',
    slug: 'leonida-map-regions',
    title: 'Leonida map: every region explained',
    kicker: 'The world',
    category: 'map',
    excerpt: 'Vice City, the Keys, Grassrivers, Port Gellhorn — what each region is, and what to expect there.',
    updatedAt: '2026-06-27',
    readingMins: 12,
    gradient: 'linear-gradient(150deg,#1FE5D6,#8A4FFF 60%,#FF2E88)',
    body: [
      { type: 'p', text: 'Grand Theft Auto VI is set in the state of Leonida, a modern reimagining of Florida centred on Vice City. Here is what we know about each named region so far.' },
      { type: 'h2', text: 'Named regions' },
      { type: 'ul', items: ['Vice City — the neon Miami analogue at the heart of the map.', 'Leonida Keys — the island chain to the south.', 'Grassrivers — the Everglades-inspired wetlands.', 'Port Gellhorn — an industrial port district.'] },
    ],
  },
];

export const MOCK_ARTICLES: Article[] = [
  {
    kind: 'article',
    slug: 'everything-confirmed',
    title: 'GTA 6: Everything confirmed so far',
    kicker: 'The big read',
    category: 'news',
    excerpt: 'The running list of what Rockstar has officially confirmed about Grand Theft Auto VI — and what is still rumour.',
    updatedAt: '2026-07-02',
    readingMins: 8,
    gradient: 'linear-gradient(150deg,#FF2E88,#8A4FFF 55%,#1FE5D6)',
    body: [
      { type: 'p', text: 'This is our living roundup of what is officially confirmed about Grand Theft Auto VI. We keep the confirmed facts strictly separate from the rumours.' },
      { type: 'h2', text: 'Confirmed' },
      { type: 'ul', items: ['Release date: Thursday 19 November 2026, on PS5 and Xbox Series X|S.', 'Dual protagonists: Jason Duval and Lucia Caminos — Lucia is the series\u2019 first playable female lead.', 'Setting: the state of Leonida, centred on a modern Vice City.', 'Editions: Standard (\u00a369.99) and Ultimate (\u00a389.99), both with the Vintage Vice City Pack as a pre-order bonus.', 'Digital pre-orders include one month of GTA+, redeemable within 180 days.', 'Pre-loading opens 12 November. Boxed copies contain a download code rather than a disc, and ship from 12 November.'] },
      { type: 'h2', text: 'Not yet confirmed' },
      { type: 'ul', items: ['A PC version — expected later, following the pattern of previous Rockstar releases, but unconfirmed.', 'Details of the online mode at launch.'] },
    ],
  },
  {
    kind: 'article',
    slug: 'which-edition-to-preorder',
    title: 'Which edition should you pre-order? (UK)',
    kicker: 'Buying',
    category: 'news',
    excerpt: 'Standard vs Ultimate, boxed vs digital, and where to pre-order in the UK — with the pricing that actually matters.',
    updatedAt: '2026-07-02',
    readingMins: 7,
    isNew: true,
    gradient: 'linear-gradient(150deg,#1FE5D6,#8A4FFF)',
    body: [
      { type: 'p', text: 'Two editions, a boxed option that is really a download code, and a handful of UK retailers. Here is how to decide.' },
      { type: 'h2', text: 'The editions' },
      { type: 'ul', items: ['Standard — \u00a369.99. The base game plus the Vintage Vice City Pack pre-order bonus.', 'Ultimate — \u00a389.99. Adds an exclusive collection of premium vehicles, weapons, apparel and customisation options for the story.'] },
      { type: 'p', text: 'One detail widely misreported elsewhere: the free month of GTA+ is not an Ultimate Edition perk. It comes with any digital pre-order, either edition, and must be redeemed within 180 days.' },
      { type: 'p', text: 'You can buy Standard now and upgrade to Ultimate later, so there is no rush to the pricier edition if you are unsure.' },
      { type: 'h2', text: 'Boxed or digital?' },
      { type: 'ul', items: ['The boxed version contains a download code — there is no disc. It ships from 12 November so you can redeem and pre-load before launch.', 'Digital pre-orders pre-load from 12 November and include the month of GTA+.'] },
    ],
  },
  {
    kind: 'article',
    slug: 'will-gta6-come-to-pc',
    title: 'Will GTA 6 come to PC? What we know',
    kicker: 'PC',
    category: 'news',
    excerpt: 'No PC version at launch — here is what history tells us about when one might arrive.',
    updatedAt: '2026-06-29',
    readingMins: 6,
    gradient: 'linear-gradient(150deg,#FF2E88,#FF9E45)',
    body: [
      { type: 'p', text: 'Grand Theft Auto VI launches on consoles only. A PC version has not been announced, but Rockstar\u2019s track record gives us a reasonable steer on what to expect.' },
    ],
  },
];
